[package]
name = "ethereum_minter"
version = "0.1.0"
authors = ["Tarik Kaced <tarik.kaced@proton.me>"]

[[target.starknet-contract]]
sierra = true
casm = true
name = "compiled"

[dependencies]
starknet = ">=2.0.2"

[cairo]
sierra-replace-ids = true
